@if(!request()->header('HX-Request'))
@extends('layouts.app')
@section('title', 'Reports')
@section('content')
@endif

<div class="space-y-6">
    {{-- Page Header --}}
    <div class="flex items-center justify-between">
        <div>
            <h1 class="text-2xl font-bold text-gray-900">Reports</h1>
            <p class="text-sm text-gray-500 mt-1">Manage and view all generated student reports</p>
        </div>
        @canany('reports.view')
        <a href="{{ route('reports.create') }}"
           hx-get="{{ route('reports.create') }}"
           hx-target="#page-content"
           hx-push-url="true"
           class="inline-flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white font-semibold px-4 py-2 rounded-lg transition-colors">
            <i class="fas fa-plus"></i>
            Generate Report
        </a>
        @endcanany
    </div>

    {{-- Flash Messages --}}
    @if(session('success'))
    <div class="bg-green-50 border border-green-200 text-green-800 rounded-lg px-4 py-3 flex items-center gap-2">
        <i class="fas fa-check-circle text-green-500"></i>
        <span>{{ session('success') }}</span>
    </div>
    @endif
    @if(session('info'))
    <div class="bg-blue-50 border border-blue-200 text-blue-800 rounded-lg px-4 py-3 flex items-center gap-2">
        <i class="fas fa-info-circle text-blue-500"></i>
        <span>{{ session('info') }}</span>
    </div>
    @endif

    {{-- Reports Table --}}
    <div class="bg-white shadow-sm rounded-xl border border-gray-200 overflow-hidden">
        @if($reports->count() > 0)
        <div class="overflow-x-auto">
            <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50">
                    <tr>
                        <th class="px-4 py-3 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Report #</th>
                        <th class="px-4 py-3 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Student</th>
                        <th class="px-4 py-3 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Term</th>
                        <th class="px-4 py-3 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Academic Year</th>
                        <th class="px-4 py-3 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Type</th>
                        <th class="px-4 py-3 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Generated By</th>
                        <th class="px-4 py-3 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Date</th>
                        <th class="px-4 py-3 text-right text-xs font-semibold text-gray-600 uppercase tracking-wider">Actions</th>
                    </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-100">
                    @foreach($reports as $report)
                    <tr class="hover:bg-gray-50 transition-colors">
                        <td class="px-4 py-3">
                            <span class="font-semibold text-blue-600">{{ $report->report_number }}</span>
                        </td>
                        <td class="px-4 py-3">
                            <div class="font-medium text-gray-900">{{ $report->student->full_name }}</div>
                            <div class="text-xs text-gray-500">{{ $report->student->student_id }}</div>
                        </td>
                        <td class="px-4 py-3 text-gray-700">{{ $report->term }}</td>
                        <td class="px-4 py-3 text-gray-700">{{ $report->academic_year }}</td>
                        <td class="px-4 py-3">
                            <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                                {{ ucwords(str_replace('_', ' ', $report->report_type)) }}
                            </span>
                        </td>
                        <td class="px-4 py-3 text-gray-700">{{ $report->generatedBy->name }}</td>
                        <td class="px-4 py-3 text-gray-500 text-sm whitespace-nowrap">
                            {{ $report->generated_at->format('M d, Y') }}
                        </td>
                        <td class="px-4 py-3 text-right">
                            <div class="flex items-center justify-end gap-2">
                                <a href="{{ route('reports.show', $report) }}"
                                   hx-get="{{ route('reports.show', $report) }}"
                                   hx-target="#page-content"
                                   hx-push-url="true"
                                   title="View"
                                   class="p-1.5 text-blue-600 hover:bg-blue-50 rounded transition-colors">
                                    <i class="fas fa-eye"></i>
                                </a>
                                <a href="{{ route('reports.print', $report) }}"
                                   target="_blank"
                                   title="Print"
                                   class="p-1.5 text-green-600 hover:bg-green-50 rounded transition-colors">
                                    <i class="fas fa-print"></i>
                                </a>
                                @canany('reports.delete')
                                <form action="{{ route('reports.destroy', $report) }}" method="POST"
                                      onsubmit="return confirm('Delete this report?')">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" title="Delete"
                                            class="p-1.5 text-red-600 hover:bg-red-50 rounded transition-colors">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </form>
                                @endcanany
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        @if($reports->hasPages())
        <div class="px-4 py-3 border-t border-gray-200">
            {{ $reports->links() }}
        </div>
        @endif
        @else
        <div class="text-center py-16">
            <i class="fas fa-file-alt text-4xl text-gray-300 mb-4"></i>
            <h3 class="text-lg font-medium text-gray-600 mb-1">No reports found</h3>
            <p class="text-gray-400 mb-4">Generate your first report to get started.</p>
            @canany('reports.view')
            <a href="{{ route('reports.create') }}"
               hx-get="{{ route('reports.create') }}"
               hx-target="#page-content"
               hx-push-url="true"
               class="inline-flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white font-semibold px-4 py-2 rounded-lg transition-colors">
                <i class="fas fa-plus"></i>
                Generate Report
            </a>
            @endcanany
        </div>
        @endif
    </div>
</div>

@if(!request()->header('HX-Request'))
@endsection
@endif
